---
- hosts: all

  vars_files:
    - manuscripts/brewkegs.yml
    - manuscripts/brewcasks.yml
    - manuscripts/brewtaps.yml
    - manuscripts/rubygems.yml
    - manuscripts/shells.yml
    - manuscripts/gitconfigs.yml

  tasks:
    - name: Setup brew taps
      homebrew_tap: "name={{ item.name }} state={{ item.state }}"
      with_items: "{{ brewtaps }}"

    - name: Install kegs with brew
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ brewkegs }}"

    - name: Install casks with brew-cask
      homebrew_cask: "name={{ item.name }} state={{ item.state }}"
      with_items: "{{ brewcasks }}"

    - name: Install Ruby gems
      gem: "name={{ item.name }} state={{ item.state }}"
      with_items: "{{ rubygems }}"

    - name: Shell executions based on file tests
      shell: "{{ item.run }} > {{ item.name}}.log"
      args:
        creates:  "{{ item.creates }}"
      with_items: "{{ filetestruns }}"

    - name: Configure git
      git_config:
        name:  "{{ item.name }}"
        scope: "{{ item.scope }}"
        value: "{{ item.value }}"
      with_items: "{{ gitconfigs }}"
