---
- hosts: localhost
  connection: local

  vars_files:
    - "{{ manuscript | default('./manuscripts/default-ubuntu.yml')}}"

  tasks:

    - name: Add apt repositories
      apt_repository:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'apt_repository') | list }}"

    - name: Install using apt
      apt:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'apt') | list }}"

    - name: Install Ruby gems
      gem:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'gem') | list }}"

    - name: Shell executions
      shell: "{{ item.shell }} > {{ item.name }}.log"
      args:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'shell') | list }}"

    - name: Configure git
      git_config:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'git_config') | list }}"

    - name: Configuration file manipulations
      lineinfile:
        "{{ item.parameters }}"
      become: "{{ item.become | default('false')}}"
      with_items: "{{ installs | selectattr('module', 'equalto', 'lineinfile') | list }}"
