---
- hosts: all
  vars_files:
    - vars/gitconfigs.yml

  tasks:
    - name: Configure git
      git_config:
        name:  "{{ item.name }}"
        scope: "{{ item.scope }}"
        value: "{{ item.value }}"
      with_items: "{{ gitconfigs }}"
